version: '3'
services:
  headersaas:
    build: ./headersAAS
    expose:
     - "8888"
    ports:
     - "8080:8888"

  headersrb:
    build: ./headersRb
    expose:
     - "80"
    ports:
     - "8081:80"

  hellopy:
    build: ./helloPy
    expose:
     - "8888"
    ports:
     - "8082:8888"

  hellorb:
    build: ./helloRb
    expose:
     - "80"
    ports:
     - "8083:80"

  mysql:
    image: "mysql:8.0.3"
    volumes:
      - ./mysql/data:/usr/share/data/
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8084:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress