apiVersion: v1
kind: Service
metadata:
  name: hellopy
  labels:
    app: hellopy
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: hellopy
    version: "1"